version: "3"

services:
  client-app:
    build:
      context: .
    image: assettwin_frontend
    container_name: assettwin_fc
    ports:
      - "3000:3000"
    command: >
      sh -c "yarn start"
    volumes:
      - ./src:/app/src
